baseurl = "http://shizone.github.io"
languageCode = "ja"
title = "SHI-Zone"
author = "Yuuki 'Razon' Sumida"

[params]
  logo      = "/images/logo.png"
  copyright = "razon All rights reserved."
  twitter   = "https://twitter.com/razon"
  facebook  = "https://www.facebook.com/shiz0ne"
  github    = "https://github.com/shizone/"
  email     = "shizonera@gmail.com"
  analytics = "UA-19371775-4"

[permalinks]
    post = "/:year/:month/:day/:filename/"