baseurl = "http://shizone.github.io"
languageCode = "ja"
title = "SHI-Zone"
author = "Yuuki 'Razon' Sumida"
copyright = "razon All rights reserved."
googleanalytics = "UA-12345678-9"
theme = "hugo-zen"

[params]
  logo      = "/images/logo.png"
  twitter   = "https://twitter.com/razon"
  facebook  = "https://www.facebook.com/shiz0ne"
  github    = "https://github.com/shizone/"
  email     = "shizonera@gmail.com"

[permalinks]
    post = "/:year/:month/:day/:filename/"