baseurl = "http://shizone.github.io"
languageCode = "ja"
title = "SHI-Zone"
googleanalytics = "UA-19371775-4"
theme = "mini"

[social]
  github = "https://github.com/shizone/"
  twitter = "https://twitter.com/razon"
  facebook = "https://www.facebook.com/shiz0ne"

[params]
  enableGoogleAnalytics = true
  author = "Yuuki 'Razon' Sumida"
  copyright = "razon All rights reserved."

[permalinks]
    post = "/:year/:month/:day/:filename/"
